### ISSUE TITLE
 datalad hirni-import-dcm >> TypeError: __call__() got an unexpected keyword argument 'native_metadata_type'

### ISSUE THREAD

**Issue by tedstrauss** [psychoinformatics-de/datalad-hirni#111]
Getting the following error. 
Running datalad 0.12.0rc4 & datalad-hirni 0.0.3.

```
# datalad --dbg hirni-import-dcm -d . --anon-subject 001 ../BMPD_P014_20190522_165435357.tar.gz acq001
Traceback (most recent call last):
  File "/root/env/datalad/bin/datalad", line 8, in <module>
    main()
  File "/root/env/datalad/lib/python3.6/site-packages/datalad/cmdline/main.py", line 500, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/root/env/datalad/lib/python3.6/site-packages/datalad/interface/base.py", line 645, in call_from_parser
    ret = list(ret)
  File "/root/env/datalad/lib/python3.6/site-packages/datalad/interface/utils.py", line 427, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/root/env/datalad/lib/python3.6/site-packages/datalad/interface/utils.py", line 520, in _process_results
    for res in results:
  File "/root/env/datalad/lib/python3.6/site-packages/datalad_hirni/commands/import_dicoms.py", line 216, in __call__
    dicom_ds = _create_subds_from_tarball(path, acq_dir)
  File "/root/env/datalad/lib/python3.6/site-packages/datalad_hirni/commands/import_dicoms.py", line 89, in _create_subds_from_tarball
    & EnsureKeyChoice('status', ('ok', 'notneeded'))
  File "/root/env/datalad/lib/python3.6/site-packages/wrapt/wrappers.py", line 564, in __call__
    args, kwargs)
  File "/root/env/datalad/lib/python3.6/site-packages/datalad/interface/utils.py", line 490, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/root/env/datalad/lib/python3.6/site-packages/wrapt/wrappers.py", line 564, in __call__
    args, kwargs)
  File "/root/env/datalad/lib/python3.6/site-packages/datalad/interface/utils.py", line 478, in return_func
    results = list(results)
  File "/root/env/datalad/lib/python3.6/site-packages/datalad/interface/utils.py", line 424, in generator_func
    wrapped(*_args, **_kwargs),
TypeError: __call__() got an unexpected keyword argument 'native_metadata_type'

> /root/env/datalad/lib/python3.6/site-packages/datalad/interface/utils.py(424)generator_func()
-> wrapped(*_args, **_kwargs),
```

**Comment by tedstrauss** [comment]
Reinstalled my virtualenv and the bug went away.
